name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: check
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint
      run: make lint

    - name: Build
      run: make build

    - name: Test
      run: make test

